name: Annotate CI run with test results
on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
permissions:
  contents: read

jobs:
  annotate:
    permissions:
      checks: write

    name: Annotate CI run with test results
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    strategy:
       fail-fast: false
       matrix:
        node-version: [18.x, 20.x, 22.x]
    timeout-minutes: 5
    steps:
      - name: Annotate CI run with test results
        uses: dorny/test-reporter@v1.8.0
        with:
          artifact: test-reports-${{ matrix.node-version }}
          name: Test Results (${{matrix.node-version}}
          path: "test-results.json"
          reporter: mocha-json